version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_python_app
    environment:
      - DATABASE_URL=postgres://db_user:db_password@db:5432/db_name
      - DEBUG=1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kia8585
      POSTGRES_DB: sky
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
